network: 'mainnet'
csrfSecret: '1nt3rn3tsc@l3'
metaChainShardId: 4294967295
api:
  public: true
  private: true
cron:
  transactionProcessor: true
  transactionProcessorMaxLookBehind: 1000
  cacheWarmer: true
urls:
  elastic:
    - 'https://search-private-mainnet-services-v2-5knapb6flvyaqdp2tmue5o6aae.eu-west-3.es.amazonaws.com/'
  gateway:
    - 'https://gateway.elrond.com'
  redis: '127.0.0.1'
  providers: 'https://internal-delegation-api.elrond.com/providers'
caching:
  cacheTtl: 6
  processTtl: 600
  poolLimit: 10
keepAliveTimeout:
  downstream_axios: 61000
  upstream_server: 60000
contracts:
  esdt: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u'
  auction: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l'
  staking: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqllls0lczs7'
  delegationManager: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqylllslmq6y6'
  delegation: 'erd1qqqqqqqqqqqqqpgqxwakt2g7u9atsnr03gqcgmhcv38pt7mkd94q6shuwt'
  delegationShardId: 2
