network: 'devnet'
metaChainShardId: 4294967295
api:
  public: true
  private: true
  auth: false
cron:
  transactionProcessor: true
  transactionProcessorMaxLookBehind: 100
  cacheWarmer: true
  fastWarm: true
  queueWorker: true
flags:
  useRequestCaching: true
  useKeepAliveAgent: true
  useTracing: false
  useRequestLogging: false
  useVmQueryTracing: false
  processNfts: true
  indexer-v3: false
image:
  width: 600
  height: 600
  type: 'png'
aws:
  s3KeyId: ''
  s3Secret: ''
  s3Bucket: 'devnet-media.elrond.com'
  s3Region: ''
urls:
  api:
    - 'https://devnet-api.elrond.com'
    - 'https://testnet-api.elrond.com'
    - 'https://api.elrond.com'
  elastic:
    - 'https://devnet-index.elrond.com'
  gateway:
    - 'https://devnet-gateway.elrond.com'
  redis: '127.0.0.1'
  rabbitmq: 'amqp://127.0.0.1:5672'
  providers: 'https://devnet-delegation.maiarbrowser.com/providers'
  media: 'https://devnet-media.elrond.com'
  nftThumbnails: 'https://devnet-media.elrond.com/nfts/thumbnail'
  tmp: '/tmp'
  ipfs: 'https://ipfs.io/ipfs'
database:
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'root'
  database: 'api'
caching:
  cacheTtl: 6
  processTtl: 600
  poolLimit: 50
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
contracts:
  esdt: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u'
  auction: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l'
  staking: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqllls0lczs7'
  delegationManager: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqylllslmq6y6'
  delegation: 'erd1qqqqqqqqqqqqqpgqp699jngundfqw07d8jzkepucvpzush6k3wvqyc44rx'
  delegationShardId: 2
inflation:
  - 1952123
  - 1746637
  - 1541150
  - 1335663
  - 1130177
  - 924690
  - 719203
security:
  admins:
  jwtSecret:
  accessAddress:
nftProcess:
  parallelism: 1
  maxRetries: 3