network: 'testnet'
csrfSecret: '1nt3rn3tsc@l3'
metaChainShardId: 4294967295
api:
  public: true
  private: true
cron:
  transactionProcessor: true
  transactionProcessorMaxLookBehind: 100
  cacheWarmer: true
urls:
  elastic:
    - 'https://testnet-index.elrond.com'
  elasticBeta:
    - 'https://search-devnet-index-test-6xy23msvwhtxjyxejqos5mv53m.eu-west-3.es.amazonaws.com'
  gateway:
    - 'https://testnet-gateway.elrond.com'
  redis: '127.0.0.1'
  providers: 'https://delegation.maiarbrowser.com/providers'
caching:
  cacheTtl: 6
  processTtl: 600
  poolLimit: 10
contracts:
  esdt: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u'
  auction: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l'
  staking: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqllls0lczs7'
  delegationManager: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqylllslmq6y6'
  delegation: 'erd1qqqqqqqqqqqqqpgqp699jngundfqw07d8jzkepucvpzush6k3wvqyc44rx'
  delegationShardId: 2