network: 'mainnet'
csrfSecret: '1nt3rn3tsc@l3'
metaChainShardId: 4294967295
api:
  public: true
  private: true
cron:
  transactionProcessor: true
  transactionProcessorMaxLookBehind: 1000
  cacheWarmer: true
urls:
  api:
    - 'https://beta-api.elrond.com'
    - 'https://devnet-beta-api.elrond.com'
    - 'https://testnet-beta-api.elrond.com'
  elastic:
    - 'https://index.elrond.com'
  gateway:
    - 'https://gateway.elrond.com'
  redis: '127.0.0.1'
  providers: 'https://internal-delegation-api.elrond.com/providers'
  dataLatestCompleteUrl: 'https://data.elrond.com/latestcomplete'
  dataLatestUrl: 'https://data.elrond.com/latest'
caching:
  cacheTtl: 6
  processTtl: 600
  poolLimit: 10
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
contracts:
  esdt: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u'
  auction: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l'
  staking: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqllls0lczs7'
  delegationManager: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqylllslmq6y6'
  delegation: 'erd1qqqqqqqqqqqqqpgqxwakt2g7u9atsnr03gqcgmhcv38pt7mkd94q6shuwt'
  delegationShardId: 2
