network: 'mainnet'
metaChainShardId: 4294967295
useLegacyElastic: false
api:
  public: true
  private: true
  auth: false
cron:
  transactionProcessor: false
  transactionProcessorMaxLookBehind: 1000
  cacheWarmer: false
  fastWarm: false
  queueWorker: true
flags:
  useRequestCaching: true
  useKeepAliveAgent: true
  useTracing: false
  useRequestLogging: false
  useVmQueryTracing: false
  processNfts: true
image:
  width: 600
  height: 600
  type: 'png'
aws:
  s3KeyId: ''
  s3Secret: ''
  s3Bucket: 'media.elrond.com'
  s3Region: ''
urls:
  api:
    - 'https://api.elrond.com'
    - 'https://devnet-api.elrond.com'
    - 'https://testnet-api.elrond.com'
  elastic:
    - 'https://index.elrond.com'
  mex:
    - 'https://mex-indexer.elrond.com'
  gateway:
    - 'https://gateway.elrond.com'
  redis: '127.0.0.1'
  providers: 'https://internal-delegation-api.elrond.com/providers'
  media: 'https://media.elrond.com'
  nftThumbnails: 'https://media.elrond.com/nfts/thumbnail'
  tmp: '/tmp'
  ipfs: 'https://ipfs.io/ipfs'
  extras: 'https://extras-api.elrond.com'
database:
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'root'
  database: 'api'
caching:
  cacheTtl: 6
  processTtl: 600
  poolLimit: 50
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
contracts:
  esdt: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u'
  auction: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l'
  staking: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqllls0lczs7'
  delegationManager: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqylllslmq6y6'
  delegation: 'erd1qqqqqqqqqqqqqpgqxwakt2g7u9atsnr03gqcgmhcv38pt7mkd94q6shuwt'
  delegationShardId: 2
inflation:
  - 1952123
  - 1746637
  - 1541150
  - 1335663
  - 1130177
  - 924690
  - 719203
security:
  admins:
  jwtSecret:
  accessAddress:
lockedAccounts:
  RIDE-7d18e9:
    - 'erd1y8tf50le8grc7t3gy7l0wk7lvg9uhzznmx66k0ma3xjguzfm752q9j2wlu'
    - 'erd12qw2g7jqtejvhq4fdtd09rpslzt5j7jausprzdru7mkuqml6pvhsp40n34'
    - 'erd10mrn7uvn0g9wqc8nnal2wedh6uj7cjg6ddpc00dsv5q0pvjdtl7s5twmj7'
    - 'erd19w6f7jqnf4nqrdmq0m548crrc4v3dmrxtn7u3dngep2r078v30aqzzu6nc'
    - 'erd1wxsug6t7zc4207th8484fm769067w5kgnurg2pmdld5nlde8zy2qklln8w'
    - 'erd1f35warttsdj4y7cz5e56xg7q32vwvfatruvu75n5d0n4zcjs3rtqptksyk'
    - 'erd188xr2v80m9tp8s0ydu7mxzq0v7rxczme39yyq3nw8k99nn4muzusp2rlyx'
    - 'erd1pjwfnd30etn6yslp4gyf9qkstjjmq5m9xyju80nnszed6gmxny6q42s6cc'
    - 'erd16davrfmlkem4cwzhcva85np7dfuhcve70293n6h3ay92r494lkpssx6t9u'
