network: 'devnet'
csrfSecret: '1nt3rn3tsc@l3'
metaChainShardId: 4294967295
api:
  public: true
  private: true
cron:
  transactionProcessor: true
  transactionProcessorMaxLookBehind: 100
  cacheWarmer: true
urls:
  api:
    - 'https://devnet-beta-api.elrond.com'
    - 'https://testnet-beta-api.elrond.com'
    - 'https://beta-api.elrond.com'
  elastic:
    - 'https://search-elrond-devnet-v2-ov66nzaicqf257tba5rctuo73m.eu-central-1.es.amazonaws.com'
  gateway:
    - 'https://devnet-gateway.elrond.com'
  redis: '127.0.0.1'
  providers: 'https://devnet-delegation.maiarbrowser.com/providers'
  dataLatestCompleteUrl: 'https://data.elrond.com/latestcomplete'
  dataLatestUrl: 'https://data.elrond.com/latest'
caching:
  cacheTtl: 6
  processTtl: 600
  poolLimit: 10
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
contracts:
  esdt: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u'
  auction: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l'
  staking: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqllls0lczs7'
  delegationManager: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqylllslmq6y6'
  delegation: 'erd1qqqqqqqqqqqqqpgqp699jngundfqw07d8jzkepucvpzush6k3wvqyc44rx'
  delegationShardId: 2
